/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package projectogasolinera;

import java.awt.Color;

/**
 *
 * @author PC19
 */
public class InterfazGasolinera extends javax.swing.JFrame {

    private MetodosGasolinera datos = new MetodosGasolinera();
    private MetodosTexto texto      = new MetodosTexto();
    private enum estadosTexto       {SELECCIONE_MEDIO_PAGO,PAGO_CREDITO,PAGO_DEBITO,PAGO_EFECTIVO,
                                    SELECCIONE_TARJETA_CREDITO, VISA_MASTER, OTRAS_TARJETAS, INGRESE_MONTO, 
                                    COMPROBAR, CARGAR, MONTO_EFECTIVO};
    private estadosTexto estado;
    private boolean[] botonEvent    = {false,false,false,false,false,false,false,false,false,false};
    private static int intentos     = 0;
    private static int auxEstados   = 0;
    
    
    public InterfazGasolinera() {
        initComponents();
        InterfazGasolinera.this.getContentPane().setBackground(Color.black);
        InterfazGasolinera.this.pack();
        inicializar();
        
        funcionPrincipal();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panelPrecioCombustible = new javax.swing.JPanel();
        jPanel4 = new javax.swing.JPanel();
        labelPrecio1 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        textoPrecio1 = new javax.swing.JTextField();
        botonSeleccion1 = new javax.swing.JButton();
        jPanel5 = new javax.swing.JPanel();
        labelPrecio2 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        textoPrecio2 = new javax.swing.JTextField();
        botonSeleccion2 = new javax.swing.JButton();
        jPanel6 = new javax.swing.JPanel();
        labelPrecio3 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        textoPrecio3 = new javax.swing.JTextField();
        botonSeleccion3 = new javax.swing.JButton();
        jPanel7 = new javax.swing.JPanel();
        labelPrecio4 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        textoPrecio4 = new javax.swing.JTextField();
        botonSeleccion4 = new javax.swing.JButton();
        jPanel8 = new javax.swing.JPanel();
        labelPrecio5 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        textoPrecio5 = new javax.swing.JTextField();
        botonSeleccion5 = new javax.swing.JButton();
        textoPrecio = new javax.swing.JTextField();
        textoLitros = new javax.swing.JTextField();
        textoPrecioPorLitro = new javax.swing.JTextField();
        panelOpciones = new javax.swing.JPanel();
        botonOpcion1 = new javax.swing.JButton();
        botonOpcion2 = new javax.swing.JButton();
        botonOpcion3 = new javax.swing.JButton();
        botonOpcion4 = new javax.swing.JButton();
        botonOpcion5 = new javax.swing.JButton();
        botonOpcion6 = new javax.swing.JButton();
        botonOpcion7 = new javax.swing.JButton();
        botonOpcion8 = new javax.swing.JButton();
        textoOpcion1 = new javax.swing.JTextField();
        textoOpcion2 = new javax.swing.JTextField();
        textoOpcion3 = new javax.swing.JTextField();
        textoOpcion4 = new javax.swing.JTextField();
        textoOpcion5 = new javax.swing.JTextField();
        textoOpcion6 = new javax.swing.JTextField();
        textoOpcion7 = new javax.swing.JTextField();
        textoOpcion8 = new javax.swing.JTextField();
        textoMenu = new javax.swing.JTextField();
        panelTeclado = new javax.swing.JPanel();
        boton1 = new javax.swing.JButton();
        boton2 = new javax.swing.JButton();
        botonBorrar = new javax.swing.JButton();
        boton4 = new javax.swing.JButton();
        boton5 = new javax.swing.JButton();
        botonLimpiar = new javax.swing.JButton();
        boton7 = new javax.swing.JButton();
        boton8 = new javax.swing.JButton();
        botonComa = new javax.swing.JButton();
        boton0 = new javax.swing.JButton();
        botonEnter = new javax.swing.JButton();
        boton9 = new javax.swing.JButton();
        boton3 = new javax.swing.JButton();
        boton6 = new javax.swing.JButton();
        textoTeclado = new javax.swing.JTextField();
        botonBombear = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Bienvenido a Codo A Codo Gas");
        setBackground(new java.awt.Color(0, 0, 0));
        setMaximumSize(new java.awt.Dimension(1000, 411));
        setMinimumSize(new java.awt.Dimension(700, 411));
        setPreferredSize(new java.awt.Dimension(700, 411));

        panelPrecioCombustible.setBackground(new java.awt.Color(0, 0, 0));

        jPanel4.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));

        labelPrecio1.setFont(new java.awt.Font("DejaVu Sans", 1, 12)); // NOI18N
        labelPrecio1.setText("Nafta Premiun");

        jLabel8.setText("precio");

        textoPrecio1.setBackground(new java.awt.Color(204, 204, 204));
        textoPrecio1.setFont(new java.awt.Font("DejaVu Sans", 1, 12)); // NOI18N
        textoPrecio1.setHorizontalAlignment(javax.swing.JTextField.RIGHT);

        botonSeleccion1.setText("seleccionar");
        botonSeleccion1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonSeleccion1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel8)
                        .addGap(26, 26, 26)
                        .addComponent(textoPrecio1))
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGap(35, 35, 35)
                        .addComponent(botonSeleccion1)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                .addGap(0, 31, Short.MAX_VALUE)
                .addComponent(labelPrecio1)
                .addGap(41, 41, 41))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(labelPrecio1, javax.swing.GroupLayout.PREFERRED_SIZE, 15, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(textoPrecio1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel8))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(botonSeleccion1)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel5.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));

        labelPrecio2.setFont(new java.awt.Font("DejaVu Sans", 1, 12)); // NOI18N
        labelPrecio2.setText("Nafta Super");

        jLabel10.setText("precio");

        textoPrecio2.setBackground(new java.awt.Color(204, 204, 204));
        textoPrecio2.setFont(new java.awt.Font("DejaVu Sans", 1, 12)); // NOI18N
        textoPrecio2.setHorizontalAlignment(javax.swing.JTextField.RIGHT);

        botonSeleccion2.setText("seleccionar");
        botonSeleccion2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonSeleccion2ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel10)
                        .addGap(26, 26, 26)
                        .addComponent(textoPrecio2))
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel5Layout.createSequentialGroup()
                                .addGap(35, 35, 35)
                                .addComponent(botonSeleccion2))
                            .addGroup(jPanel5Layout.createSequentialGroup()
                                .addGap(47, 47, 47)
                                .addComponent(labelPrecio2)))
                        .addGap(0, 32, Short.MAX_VALUE)))
                .addContainerGap())
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(labelPrecio2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(textoPrecio2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel10))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(botonSeleccion2)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel6.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));

        labelPrecio3.setFont(new java.awt.Font("DejaVu Sans", 1, 12)); // NOI18N
        labelPrecio3.setText("Infinia");

        jLabel12.setText("precio");

        textoPrecio3.setBackground(new java.awt.Color(204, 204, 204));
        textoPrecio3.setFont(new java.awt.Font("DejaVu Sans", 1, 12)); // NOI18N
        textoPrecio3.setHorizontalAlignment(javax.swing.JTextField.RIGHT);

        botonSeleccion3.setText("seleccionar");
        botonSeleccion3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonSeleccion3ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel12)
                .addGap(26, 26, 26)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel6Layout.createSequentialGroup()
                        .addComponent(labelPrecio3)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addComponent(textoPrecio3))
                .addContainerGap())
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addGap(35, 35, 35)
                .addComponent(botonSeleccion3)
                .addContainerGap(38, Short.MAX_VALUE))
        );
        jPanel6Layout.setVerticalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(labelPrecio3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(textoPrecio3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel12))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(botonSeleccion3)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel7.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));

        labelPrecio4.setFont(new java.awt.Font("DejaVu Sans", 1, 12)); // NOI18N
        labelPrecio4.setText("Diesel 500");

        jLabel14.setText("precio");

        textoPrecio4.setBackground(new java.awt.Color(204, 204, 204));
        textoPrecio4.setFont(new java.awt.Font("DejaVu Sans", 1, 12)); // NOI18N
        textoPrecio4.setHorizontalAlignment(javax.swing.JTextField.RIGHT);

        botonSeleccion4.setText("seleccionar");
        botonSeleccion4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonSeleccion4ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel7Layout = new javax.swing.GroupLayout(jPanel7);
        jPanel7.setLayout(jPanel7Layout);
        jPanel7Layout.setHorizontalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel7Layout.createSequentialGroup()
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel7Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel14)
                        .addGap(26, 26, 26)
                        .addComponent(textoPrecio4))
                    .addGroup(jPanel7Layout.createSequentialGroup()
                        .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel7Layout.createSequentialGroup()
                                .addGap(35, 35, 35)
                                .addComponent(botonSeleccion4))
                            .addGroup(jPanel7Layout.createSequentialGroup()
                                .addGap(53, 53, 53)
                                .addComponent(labelPrecio4)))
                        .addGap(0, 32, Short.MAX_VALUE)))
                .addContainerGap())
        );
        jPanel7Layout.setVerticalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel7Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(labelPrecio4)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(textoPrecio4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel14))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(botonSeleccion4)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel8.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));

        labelPrecio5.setFont(new java.awt.Font("DejaVu Sans", 1, 12)); // NOI18N
        labelPrecio5.setText("Euro Diesel");

        jLabel16.setText("precio");

        textoPrecio5.setBackground(new java.awt.Color(204, 204, 204));
        textoPrecio5.setFont(new java.awt.Font("DejaVu Sans", 1, 12)); // NOI18N
        textoPrecio5.setHorizontalAlignment(javax.swing.JTextField.RIGHT);

        botonSeleccion5.setText("seleccionar");
        botonSeleccion5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonSeleccion5ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel8Layout = new javax.swing.GroupLayout(jPanel8);
        jPanel8.setLayout(jPanel8Layout);
        jPanel8Layout.setHorizontalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel8Layout.createSequentialGroup()
                .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel8Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel16)
                        .addGap(26, 26, 26)
                        .addComponent(textoPrecio5))
                    .addGroup(jPanel8Layout.createSequentialGroup()
                        .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel8Layout.createSequentialGroup()
                                .addGap(35, 35, 35)
                                .addComponent(botonSeleccion5))
                            .addGroup(jPanel8Layout.createSequentialGroup()
                                .addGap(48, 48, 48)
                                .addComponent(labelPrecio5)))
                        .addGap(0, 32, Short.MAX_VALUE)))
                .addContainerGap())
        );
        jPanel8Layout.setVerticalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel8Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(labelPrecio5)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(textoPrecio5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel16))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(botonSeleccion5)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout panelPrecioCombustibleLayout = new javax.swing.GroupLayout(panelPrecioCombustible);
        panelPrecioCombustible.setLayout(panelPrecioCombustibleLayout);
        panelPrecioCombustibleLayout.setHorizontalGroup(
            panelPrecioCombustibleLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelPrecioCombustibleLayout.createSequentialGroup()
                .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel8, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        panelPrecioCombustibleLayout.setVerticalGroup(
            panelPrecioCombustibleLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addComponent(jPanel6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addComponent(jPanel7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addComponent(jPanel8, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        textoPrecio.setBackground(new java.awt.Color(204, 204, 204));
        textoPrecio.setFont(new java.awt.Font("DejaVu Sans", 1, 18)); // NOI18N
        textoPrecio.setHorizontalAlignment(javax.swing.JTextField.RIGHT);

        textoLitros.setBackground(new java.awt.Color(204, 204, 204));
        textoLitros.setFont(new java.awt.Font("DejaVu Sans", 1, 18)); // NOI18N
        textoLitros.setHorizontalAlignment(javax.swing.JTextField.RIGHT);

        textoPrecioPorLitro.setBackground(new java.awt.Color(204, 204, 204));
        textoPrecioPorLitro.setFont(new java.awt.Font("DejaVu Serif Condensed", 1, 18)); // NOI18N
        textoPrecioPorLitro.setHorizontalAlignment(javax.swing.JTextField.RIGHT);

        panelOpciones.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));

        botonOpcion1.setPreferredSize(new java.awt.Dimension(40, 40));
        botonOpcion1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonOpcion1ActionPerformed(evt);
            }
        });

        botonOpcion2.setPreferredSize(new java.awt.Dimension(40, 40));
        botonOpcion2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonOpcion2ActionPerformed(evt);
            }
        });

        botonOpcion3.setPreferredSize(new java.awt.Dimension(40, 40));
        botonOpcion3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonOpcion3ActionPerformed(evt);
            }
        });

        botonOpcion4.setPreferredSize(new java.awt.Dimension(40, 40));
        botonOpcion4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonOpcion4ActionPerformed(evt);
            }
        });

        botonOpcion5.setPreferredSize(new java.awt.Dimension(40, 40));
        botonOpcion5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonOpcion5ActionPerformed(evt);
            }
        });

        botonOpcion6.setPreferredSize(new java.awt.Dimension(40, 40));
        botonOpcion6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonOpcion6ActionPerformed(evt);
            }
        });

        botonOpcion7.setPreferredSize(new java.awt.Dimension(40, 40));
        botonOpcion7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonOpcion7ActionPerformed(evt);
            }
        });

        botonOpcion8.setPreferredSize(new java.awt.Dimension(40, 40));
        botonOpcion8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonOpcion8ActionPerformed(evt);
            }
        });

        textoOpcion1.setBackground(new java.awt.Color(204, 204, 204));
        textoOpcion1.setFont(new java.awt.Font("DejaVu Sans", 1, 12)); // NOI18N

        textoOpcion2.setBackground(new java.awt.Color(204, 204, 204));
        textoOpcion2.setFont(new java.awt.Font("DejaVu Sans", 1, 12)); // NOI18N

        textoOpcion3.setBackground(new java.awt.Color(204, 204, 204));
        textoOpcion3.setFont(new java.awt.Font("DejaVu Sans", 1, 12)); // NOI18N

        textoOpcion4.setBackground(new java.awt.Color(204, 204, 204));
        textoOpcion4.setFont(new java.awt.Font("DejaVu Sans", 1, 12)); // NOI18N

        textoOpcion5.setBackground(new java.awt.Color(204, 204, 204));
        textoOpcion5.setFont(new java.awt.Font("DejaVu Sans", 1, 12)); // NOI18N
        textoOpcion5.setHorizontalAlignment(javax.swing.JTextField.RIGHT);

        textoOpcion6.setBackground(new java.awt.Color(204, 204, 204));
        textoOpcion6.setFont(new java.awt.Font("DejaVu Sans", 1, 12)); // NOI18N
        textoOpcion6.setHorizontalAlignment(javax.swing.JTextField.RIGHT);

        textoOpcion7.setBackground(new java.awt.Color(204, 204, 204));
        textoOpcion7.setFont(new java.awt.Font("DejaVu Sans", 1, 12)); // NOI18N
        textoOpcion7.setHorizontalAlignment(javax.swing.JTextField.RIGHT);

        textoOpcion8.setBackground(new java.awt.Color(204, 204, 204));
        textoOpcion8.setFont(new java.awt.Font("DejaVu Sans", 1, 12)); // NOI18N
        textoOpcion8.setHorizontalAlignment(javax.swing.JTextField.RIGHT);

        textoMenu.setBackground(new java.awt.Color(204, 204, 204));
        textoMenu.setFont(new java.awt.Font("DejaVu Sans", 1, 14)); // NOI18N
        textoMenu.setHorizontalAlignment(javax.swing.JTextField.CENTER);

        javax.swing.GroupLayout panelOpcionesLayout = new javax.swing.GroupLayout(panelOpciones);
        panelOpciones.setLayout(panelOpcionesLayout);
        panelOpcionesLayout.setHorizontalGroup(
            panelOpcionesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelOpcionesLayout.createSequentialGroup()
                .addGroup(panelOpcionesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(textoMenu, javax.swing.GroupLayout.PREFERRED_SIZE, 390, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(panelOpcionesLayout.createSequentialGroup()
                        .addGroup(panelOpcionesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(panelOpcionesLayout.createSequentialGroup()
                                .addGap(49, 49, 49)
                                .addGroup(panelOpcionesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(textoOpcion2, javax.swing.GroupLayout.DEFAULT_SIZE, 144, Short.MAX_VALUE)
                                    .addComponent(textoOpcion3)
                                    .addComponent(textoOpcion4)
                                    .addComponent(textoOpcion1)))
                            .addGroup(panelOpcionesLayout.createSequentialGroup()
                                .addGap(3, 3, 3)
                                .addComponent(botonOpcion2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(panelOpcionesLayout.createSequentialGroup()
                                .addGap(3, 3, 3)
                                .addComponent(botonOpcion4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(panelOpcionesLayout.createSequentialGroup()
                                .addGap(3, 3, 3)
                                .addComponent(botonOpcion3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(panelOpcionesLayout.createSequentialGroup()
                                .addGap(3, 3, 3)
                                .addComponent(botonOpcion1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(panelOpcionesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelOpcionesLayout.createSequentialGroup()
                                .addComponent(textoOpcion8)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(botonOpcion8, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelOpcionesLayout.createSequentialGroup()
                                .addComponent(textoOpcion7)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(botonOpcion7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelOpcionesLayout.createSequentialGroup()
                                .addComponent(textoOpcion6)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(botonOpcion6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelOpcionesLayout.createSequentialGroup()
                                .addComponent(textoOpcion5, javax.swing.GroupLayout.PREFERRED_SIZE, 145, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(botonOpcion5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addContainerGap())
        );
        panelOpcionesLayout.setVerticalGroup(
            panelOpcionesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelOpcionesLayout.createSequentialGroup()
                .addComponent(textoMenu, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(panelOpcionesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panelOpcionesLayout.createSequentialGroup()
                        .addGap(9, 9, 9)
                        .addComponent(botonOpcion1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(51, 51, 51)
                        .addGroup(panelOpcionesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(textoOpcion3, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(textoOpcion7, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(panelOpcionesLayout.createSequentialGroup()
                        .addGap(100, 100, 100)
                        .addComponent(botonOpcion3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(panelOpcionesLayout.createSequentialGroup()
                        .addGap(146, 146, 146)
                        .addComponent(botonOpcion4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(panelOpcionesLayout.createSequentialGroup()
                        .addGap(54, 54, 54)
                        .addComponent(botonOpcion2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(panelOpcionesLayout.createSequentialGroup()
                        .addGap(54, 54, 54)
                        .addGroup(panelOpcionesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(textoOpcion2, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(textoOpcion6, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(panelOpcionesLayout.createSequentialGroup()
                        .addGap(146, 146, 146)
                        .addComponent(textoOpcion4, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(panelOpcionesLayout.createSequentialGroup()
                        .addGap(9, 9, 9)
                        .addGroup(panelOpcionesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(panelOpcionesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(textoOpcion1, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(textoOpcion5, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(panelOpcionesLayout.createSequentialGroup()
                                .addComponent(botonOpcion5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(5, 5, 5)
                                .addComponent(botonOpcion6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(botonOpcion7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(6, 6, 6)
                                .addGroup(panelOpcionesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(textoOpcion8, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(botonOpcion8, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        panelTeclado.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));

        boton1.setText("1");
        boton1.setPreferredSize(new java.awt.Dimension(45, 45));
        boton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                boton1ActionPerformed(evt);
            }
        });

        boton2.setText("2");
        boton2.setPreferredSize(new java.awt.Dimension(45, 45));
        boton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                boton2ActionPerformed(evt);
            }
        });

        botonBorrar.setText("BORRAR");
        botonBorrar.setPreferredSize(new java.awt.Dimension(40, 40));
        botonBorrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonBorrarActionPerformed(evt);
            }
        });

        boton4.setText("4");
        boton4.setPreferredSize(new java.awt.Dimension(45, 45));
        boton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                boton4ActionPerformed(evt);
            }
        });

        boton5.setText("5");
        boton5.setPreferredSize(new java.awt.Dimension(45, 45));
        boton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                boton5ActionPerformed(evt);
            }
        });

        botonLimpiar.setText("LIMPIAR");
        botonLimpiar.setPreferredSize(new java.awt.Dimension(40, 40));
        botonLimpiar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonLimpiarActionPerformed(evt);
            }
        });

        boton7.setText("7");
        boton7.setPreferredSize(new java.awt.Dimension(45, 45));
        boton7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                boton7ActionPerformed(evt);
            }
        });

        boton8.setText("8");
        boton8.setPreferredSize(new java.awt.Dimension(45, 45));
        boton8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                boton8ActionPerformed(evt);
            }
        });

        botonComa.setText(",");
        botonComa.setPreferredSize(new java.awt.Dimension(40, 40));
        botonComa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonComaActionPerformed(evt);
            }
        });

        boton0.setText("0");
        boton0.setPreferredSize(new java.awt.Dimension(45, 45));
        boton0.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                boton0ActionPerformed(evt);
            }
        });

        botonEnter.setText("ENTER");
        botonEnter.setPreferredSize(new java.awt.Dimension(40, 40));
        botonEnter.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonEnterActionPerformed(evt);
            }
        });

        boton9.setText("9");
        boton9.setPreferredSize(new java.awt.Dimension(45, 45));
        boton9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                boton9ActionPerformed(evt);
            }
        });

        boton3.setText("3");
        boton3.setPreferredSize(new java.awt.Dimension(45, 45));
        boton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                boton3ActionPerformed(evt);
            }
        });

        boton6.setText("6");
        boton6.setPreferredSize(new java.awt.Dimension(45, 45));
        boton6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                boton6ActionPerformed(evt);
            }
        });

        textoTeclado.setBackground(new java.awt.Color(204, 204, 204));
        textoTeclado.setFont(new java.awt.Font("DejaVu Sans", 1, 12)); // NOI18N
        textoTeclado.setHorizontalAlignment(javax.swing.JTextField.RIGHT);

        javax.swing.GroupLayout panelTecladoLayout = new javax.swing.GroupLayout(panelTeclado);
        panelTeclado.setLayout(panelTecladoLayout);
        panelTecladoLayout.setHorizontalGroup(
            panelTecladoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelTecladoLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panelTecladoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(textoTeclado)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelTecladoLayout.createSequentialGroup()
                        .addGroup(panelTecladoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(panelTecladoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(panelTecladoLayout.createSequentialGroup()
                                    .addComponent(boton1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(boton2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGroup(panelTecladoLayout.createSequentialGroup()
                                    .addComponent(boton4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(boton5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGroup(panelTecladoLayout.createSequentialGroup()
                                    .addComponent(boton7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(boton8, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addComponent(boton0, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(panelTecladoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(boton9, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(boton3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(boton6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(panelTecladoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(botonBorrar, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 118, Short.MAX_VALUE)
                            .addComponent(botonLimpiar, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(botonComa, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(botonEnter, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                .addContainerGap())
        );
        panelTecladoLayout.setVerticalGroup(
            panelTecladoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelTecladoLayout.createSequentialGroup()
                .addComponent(textoTeclado, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(panelTecladoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panelTecladoLayout.createSequentialGroup()
                        .addComponent(boton3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(boton6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(boton9, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(panelTecladoLayout.createSequentialGroup()
                        .addGroup(panelTecladoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(boton1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(boton2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(botonBorrar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(panelTecladoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(boton4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(boton5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(botonLimpiar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(panelTecladoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(boton7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(boton8, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(botonComa, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(panelTecladoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(boton0, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(botonEnter, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        botonBombear.setText("BOMBEAR");
        botonBombear.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonBombearActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("DejaVu Sans", 1, 12)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 0, 0));
        jLabel1.setText("Precio");

        jLabel2.setFont(new java.awt.Font("DejaVu Sans", 1, 12)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 0, 0));
        jLabel2.setText("Litros");

        jLabel3.setFont(new java.awt.Font("DejaVu Sans", 1, 12)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 0, 0));
        jLabel3.setText("Precio por litro");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(panelPrecioCombustible, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 25, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(panelOpciones, javax.swing.GroupLayout.PREFERRED_SIZE, 400, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(panelTeclado, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(textoPrecioPorLitro, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 153, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel3, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel2, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel1, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(textoLitros, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(botonBombear, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 197, Short.MAX_VALUE)
                            .addComponent(textoPrecio, javax.swing.GroupLayout.Alignment.TRAILING))))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addGap(7, 7, 7)
                        .addComponent(textoPrecio, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jLabel2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(textoLitros, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel3)
                        .addGap(6, 6, 6)
                        .addComponent(textoPrecioPorLitro, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(6, 6, 6)
                        .addComponent(botonBombear))
                    .addComponent(panelTeclado, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(panelOpciones, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(26, 26, 26)
                .addComponent(panelPrecioCombustible, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
        
    //
    //inicializadores propios
    //
    private void inicializar(){
        textoPrecio1.setText(MetodosTexto.PRECIO_NAFTA_SUPER);
        textoPrecio2.setText(MetodosTexto.PRECIO_NAFTA_PREMIUN);
        textoPrecio3.setText(MetodosTexto.PRECIO_INFINIA);
        textoPrecio4.setText(MetodosTexto.PRECIO_EURO_DIESEL);
        textoPrecio5.setText(MetodosTexto.PRECIO_DIESEL500);
        botonBombear.setEnabled(false);
        setTeclado(false);
        panelTeclado.setVisible(false);
        panelPrecioCombustible.setVisible(false);
        estado = estadosTexto.SELECCIONE_MEDIO_PAGO;
    }
    
    //
    //funcion principal
    //
    public void funcionPrincipal(){
        switch(estado){
            case SELECCIONE_MEDIO_PAGO:
                if(auxEstados == 0){
                    limpiarPantalla();
                    textoMenu.setText(MetodosTexto.MEDIO_DE_PAGO);
                    textoOpcion6.setText(MetodosTexto.OPCION_CREDITO);
                    textoOpcion7.setText(MetodosTexto.OPCION_DEBITO);
                    textoOpcion8.setText(MetodosTexto.OPCION_EFECTIVO); 
                    auxEstados = 1;
                }
                
                if(botonEvent[5] == false){                            //este if no tiene motivo logico de estar pero el programa no 
                     textoMenu.setText(textoMenu.getText()+"");        //detecta ningun otro if si no esta
                }
                
                if(botonEvent[5] == true){
                    limpiarBufferBotones();
                    estado = estadosTexto.PAGO_CREDITO;
                    auxEstados = 0;
                }
                if(botonEvent[6] == true){
                    limpiarBufferBotones();
                    estado = estadosTexto.PAGO_DEBITO; 
                    auxEstados = 0;
                }
                if(botonEvent[7] == true){
                    limpiarBufferBotones();
                    textoPrecio.setText("");
                    textoLitros.setText("");
                    textoPrecioPorLitro.setText("");
                    estado = estadosTexto.PAGO_EFECTIVO; 
                    auxEstados = 0;
                }
                break;
                    
            case PAGO_CREDITO: 
                if(auxEstados == 0){
                    limpiarPantalla();
                    textoMenu.setText(MetodosTexto.SELECCION_CREDITO);
                    textoOpcion1.setText(MetodosTexto.VISA);
                    textoOpcion2.setText(MetodosTexto.MASTERCARD);
                    textoOpcion3.setText(MetodosTexto.AMERICAN);
                    textoOpcion4.setText(MetodosTexto.NARANJA);
                    textoOpcion5.setText(MetodosTexto.CENCOSUD);
                    textoOpcion8.setText(MetodosTexto.VOLVER); 
                    auxEstados = 1;
                }
                
                if((botonEvent[0] == true)||(botonEvent[1] == true)){
                    limpiarBufferBotones();
                    estado = estadosTexto.VISA_MASTER; 
                    auxEstados = 0;
                }
                if((botonEvent[2] == true)||(botonEvent[3] == true)||(botonEvent[4] == true)){
                    limpiarBufferBotones();
                    estado = estadosTexto.OTRAS_TARJETAS; 
                    auxEstados = 0;
                }
                
                if(botonEvent[7] == true){
                    limpiarBufferBotones();
                    textoPrecio.setText("");
                    textoLitros.setText("");
                    textoPrecioPorLitro.setText("");
                    estado = estadosTexto.SELECCIONE_MEDIO_PAGO; 
                    auxEstados = 0;
                }
                break;
                
            case PAGO_DEBITO:
                datos.setRecargo(0);
                estado = estadosTexto.INGRESE_MONTO; 
                break;
                
            case PAGO_EFECTIVO:
                if(auxEstados == 0){
                    limpiarPantalla();
                    textoMenu.setText(MetodosTexto.CODIGO_EFECTIVO);
                    panelTeclado.setVisible(true);
                    setTeclado(true);
                    setTecladoCodigo();
                    textoOpcion8.setText(MetodosTexto.VOLVER); 
                    auxEstados = 1;
                }
                
                
                if(botonEvent[8] == true){
                    limpiarBufferBotones();
                    if((datos.comprobarCodigo((int)datos.getValorNumerico())!= true)&&(intentos < 2)){
                        intentos++;
                        textoMenu.setText("intentos: " + intentos + " Max: 3");
                    }else if((datos.comprobarCodigo((int)datos.getValorNumerico())!= true)&&(intentos >= 2)){
                        estado = estadosTexto.SELECCIONE_MEDIO_PAGO;
                        intentos = 0;
                        auxEstados = 0;
                    }else{
                        datos.setRecargo(0);
                        estado = estadosTexto.MONTO_EFECTIVO;
                        intentos = 0;
                        auxEstados = 0;
                    }
                }
                
                if(botonEvent[7] == true){
                    limpiarBufferBotones();
                    textoPrecio.setText("");
                    textoLitros.setText("");
                    textoPrecioPorLitro.setText("");
                    panelTeclado.setVisible(false);
                    setTeclado(false);
                    estado = estadosTexto.SELECCIONE_MEDIO_PAGO; 
                    auxEstados = 0;
                }
                break;
            
            case VISA_MASTER:
                if(auxEstados == 0){
                    limpiarPantalla();
                    textoMenu.setText(MetodosTexto.INGRESE_CUOTAS_VM);
                    panelTeclado.setVisible(true);
                    setTeclado(true);
                    setTecladoCuotaVisa();
                    textoOpcion8.setText(MetodosTexto.VOLVER); 
                    auxEstados = 1;
                }
                limitTeclado();
                
                if(botonEvent[8] == true){
                    limpiarBufferBotones();
                    datos.setRecargo(1);
                    estado = estadosTexto.INGRESE_MONTO; 
                    auxEstados = 0;
                }
                if(botonEvent[7] == true){
                    limpiarBufferBotones();
                    textoPrecio.setText("");
                    textoLitros.setText("");
                    textoPrecioPorLitro.setText("");
                    panelTeclado.setVisible(false);
                    setTeclado(false);
                    estado = estadosTexto.SELECCIONE_MEDIO_PAGO; 
                    auxEstados = 0;
                }
                break;
            
            case OTRAS_TARJETAS:
                if(auxEstados == 0){
                    limpiarPantalla();
                    textoMenu.setText(MetodosTexto.INGRESE_CUOTAS_OTRAS);
                    panelTeclado.setVisible(true);
                    setTeclado(true);
                    setTecladoCuotaOtros();
                    textoOpcion8.setText(MetodosTexto.VOLVER); 
                    auxEstados = 1;
                }
                limitTeclado();
                
                if(botonEvent[8] == true){
                    limpiarBufferBotones();
                    datos.setRecargo(2);
                    estado = estadosTexto.INGRESE_MONTO; 
                    auxEstados = 0;
                }
                if(botonEvent[7] == true){
                    limpiarBufferBotones();
                    textoPrecio.setText("");
                    textoLitros.setText("");
                    textoPrecioPorLitro.setText("");
                    panelTeclado.setVisible(false);
                    setTeclado(false);
                    estado = estadosTexto.SELECCIONE_MEDIO_PAGO; 
                    auxEstados = 0;
                }
                break;
                
            case MONTO_EFECTIVO:
                if(auxEstados == 0){
                        limpiarPantalla();
                        panelTeclado.setVisible(false);
                        setTeclado(false);
                        panelPrecioCombustible.setVisible(true);
                        textoMenu.setText(MetodosTexto.SELECCIONE_COMBUSTIBLE);
                        textoOpcion8.setText(MetodosTexto.VOLVER); 
                        auxEstados = 1;
                    }
                
                if(textoPrecioPorLitro.getText().length() != 0){
                    limpiarBufferBotones();
                    datos.setLitrosIgresados();
                    datos.setMontoPagar();
                    setTeclado(false);
                    panelPrecioCombustible.setVisible(false);
                    textoPrecio.setText("" + datos.getMontoAPagar());
                    textoLitros.setText("" + datos.getLitrosIngresados());
                    estado = estadosTexto.COMPROBAR; 
                    auxEstados = 0;
                }
                if(botonEvent[7] == true){
                    limpiarBufferBotones();
                    textoPrecio.setText("");
                    textoLitros.setText("");
                    textoPrecioPorLitro.setText("");
                    panelTeclado.setVisible(false);
                    panelPrecioCombustible.setVisible(false);
                    setTeclado(false);
                    estado = estadosTexto.SELECCIONE_MEDIO_PAGO; 
                    auxEstados = 0;
                }
                break;
                
            case INGRESE_MONTO:
                    if(auxEstados == 0){
                        limpiarPantalla();
                        textoMenu.setText(MetodosTexto.INGRESE_MONTO);
                        setTeclado(true);
                        panelTeclado.setVisible(true);
                        panelPrecioCombustible.setVisible(true);
                        textoOpcion8.setText(MetodosTexto.VOLVER); 
                        auxEstados = 1;
                    }
                    
                    if((botonEvent[8] == true)&&(textoPrecioPorLitro.getText().length() != 0)){
                        limpiarBufferBotones();
                        datos.setLitrosIgresados();
                        datos.setMontoPagar();
                        setTeclado(false);
                        panelTeclado.setVisible(false);
                        panelPrecioCombustible.setVisible(false);
                        textoPrecio.setText("" + datos.getMontoAPagar());
                        textoLitros.setText("" + datos.getLitrosIngresados());
                        estado = estadosTexto.COMPROBAR; 
                        auxEstados = 0;
                    }
                    if((botonEvent[8] == true)&&(textoPrecioPorLitro.getText().length() == 0)){
                        limpiarBufferBotones();
                    }
                    
                    if(botonEvent[7] == true){
                        limpiarBufferBotones();
                        textoPrecio.setText("");
                        textoLitros.setText("");
                        textoPrecioPorLitro.setText("");
                        setTeclado(false);
                        panelTeclado.setVisible(false);
                        panelPrecioCombustible.setVisible(false);
                        estado = estadosTexto.SELECCIONE_MEDIO_PAGO; 
                        auxEstados = 0;
                    }
                    
                break;
                
            case COMPROBAR:
                    if(auxEstados == 0){
                        limpiarPantalla();
                        panelTeclado.setVisible(false);
                        textoMenu.setText(MetodosTexto.COMPROBAR);
                        textoOpcion7.setText(MetodosTexto.CONTINUAR); 
                        textoOpcion8.setText(MetodosTexto.VOLVER); 
                        auxEstados = 1;
                    }
                    if(botonEvent[6] == true){
                        estado = estadosTexto.CARGAR; 
                        auxEstados = 0;
                    }
                    if(botonEvent[7] == true){
                        limpiarBufferBotones();
                        textoPrecio.setText("");
                        textoLitros.setText("");
                        textoPrecioPorLitro.setText("");
                        setTeclado(false);
                        estado = estadosTexto.SELECCIONE_MEDIO_PAGO; 
                        auxEstados = 0;
                    }
                break;
                
            case CARGAR:
                    if(auxEstados == 0){
                        limpiarPantalla();
                        botonBombear.setEnabled(true);
                        textoMenu.setText(MetodosTexto.ESPERE); 
                        auxEstados = 1;
                    }
                    
                    if((botonEvent[9] == true)&&(intentos < 1)){
                        limpiarPantalla();
                        limpiarBufferBotones();
                        textoPrecio.setText("");
                        textoLitros.setText("");
                        textoPrecioPorLitro.setText("");
                        textoMenu.setText(MetodosTexto.GRACIAS);
                        botonBombear.setText("FINALIZAR");
                        intentos++;
                    }
                    
                    if((botonEvent[9] == true)&&(intentos > 0)){
                        botonBombear.setText("BOMBEAR");
                        botonBombear.setEnabled(false);
                        estado = estadosTexto.SELECCIONE_MEDIO_PAGO;
                        intentos = 0;
                        auxEstados = 0;
                    }
                    
                break;
                
        }
    }
    private void limpiarBufferBotones(){
        for(int i = 0; i < botonEvent.length;++i){
            botonEvent[i] = false;
        }
    }
    
    private void limpiarPantalla(){
        textoMenu.setText("");
        textoOpcion1.setText("");
        textoOpcion2.setText("");
        textoOpcion3.setText("");
        textoOpcion4.setText("");
        textoOpcion5.setText("");
        textoOpcion6.setText("");
        textoOpcion7.setText("");
        textoOpcion8.setText("");
    }
    
    private void setTecladoCodigo(){
        botonComa.setEnabled(false);
    }
    private void setTecladoCuotaVisa(){
        botonComa.setEnabled(false);
        boton7.setEnabled(false);
        boton8.setEnabled(false);
        boton9.setEnabled(false);
        boton0.setEnabled(false);
    }
    private void setTecladoCuotaOtros(){
        botonComa.setEnabled(false);
        boton3.setEnabled(false);
        boton4.setEnabled(false);
        boton5.setEnabled(false);
        boton6.setEnabled(false);
        boton7.setEnabled(false);
        boton8.setEnabled(false);
        boton9.setEnabled(false);
        boton0.setEnabled(false);
    }
    
    private void setTeclado(boolean modo){
        botonComa.setEnabled(modo);
        botonEnter.setEnabled(modo);
        botonBorrar.setEnabled(modo);
        botonLimpiar.setEnabled(modo);
        boton1.setEnabled(modo);
        boton2.setEnabled(modo);
        boton3.setEnabled(modo);
        boton4.setEnabled(modo);
        boton5.setEnabled(modo);
        boton6.setEnabled(modo);
        boton7.setEnabled(modo);
        boton8.setEnabled(modo);
        boton9.setEnabled(modo);
        boton0.setEnabled(modo);
    }
    
    private void limitTeclado(){
        if(textoTeclado.getText().length() >= 1){
            boton1.setEnabled(false);
            boton2.setEnabled(false);
            boton3.setEnabled(false);
            boton4.setEnabled(false);
            boton5.setEnabled(false);
            boton6.setEnabled(false);
            boton7.setEnabled(false);
            boton8.setEnabled(false);
            boton9.setEnabled(false);
            boton0.setEnabled(false);
            botonBorrar.setEnabled(false);
            botonLimpiar.setEnabled(false);
        }
    }
    //
    //Botones teclado numerico
    //
    private void boton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_boton1ActionPerformed
        datos.setValorTecladoNumerico(datos.getValorTecladoNumerico() + 1);
        textoTeclado.setText(datos.getValorTecladoNumerico());
    }//GEN-LAST:event_boton1ActionPerformed

    private void boton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_boton2ActionPerformed
        datos.setValorTecladoNumerico(datos.getValorTecladoNumerico() + 2);
        textoTeclado.setText(datos.getValorTecladoNumerico());
    }//GEN-LAST:event_boton2ActionPerformed

    private void boton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_boton3ActionPerformed
        datos.setValorTecladoNumerico(datos.getValorTecladoNumerico() + 3);
        textoTeclado.setText(datos.getValorTecladoNumerico());
    }//GEN-LAST:event_boton3ActionPerformed

    private void boton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_boton4ActionPerformed
        datos.setValorTecladoNumerico(datos.getValorTecladoNumerico() + 4);
        textoTeclado.setText(datos.getValorTecladoNumerico());
    }//GEN-LAST:event_boton4ActionPerformed

    private void boton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_boton5ActionPerformed
        datos.setValorTecladoNumerico(datos.getValorTecladoNumerico() + 5);
        textoTeclado.setText(datos.getValorTecladoNumerico());
    }//GEN-LAST:event_boton5ActionPerformed

    private void boton6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_boton6ActionPerformed
        datos.setValorTecladoNumerico(datos.getValorTecladoNumerico() + 6);
        textoTeclado.setText(datos.getValorTecladoNumerico());
    }//GEN-LAST:event_boton6ActionPerformed

    private void boton7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_boton7ActionPerformed
        datos.setValorTecladoNumerico(datos.getValorTecladoNumerico() + 7);
        textoTeclado.setText(datos.getValorTecladoNumerico());
    }//GEN-LAST:event_boton7ActionPerformed

    private void boton8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_boton8ActionPerformed
        datos.setValorTecladoNumerico(datos.getValorTecladoNumerico() + 8);
        textoTeclado.setText(datos.getValorTecladoNumerico());
    }//GEN-LAST:event_boton8ActionPerformed

    private void boton9ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_boton9ActionPerformed
        datos.setValorTecladoNumerico(datos.getValorTecladoNumerico() + 9);
        textoTeclado.setText(datos.getValorTecladoNumerico());
    }//GEN-LAST:event_boton9ActionPerformed

    private void boton0ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_boton0ActionPerformed
        datos.setValorTecladoNumerico(datos.getValorTecladoNumerico() + 0);
        textoTeclado.setText(datos.getValorTecladoNumerico());
    }//GEN-LAST:event_boton0ActionPerformed

    private void botonBorrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonBorrarActionPerformed
        String cadena = datos.getValorTecladoNumerico();
        
        if(cadena.length() != 0){
            cadena = cadena.substring(0, cadena.length() -1);
            datos.setValorTecladoNumerico(cadena);
            textoTeclado.setText(datos.getValorTecladoNumerico());
            
        }
    }//GEN-LAST:event_botonBorrarActionPerformed

    private void botonLimpiarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonLimpiarActionPerformed
        datos.setValorTecladoNumerico("");
        textoTeclado.setText(datos.getValorTecladoNumerico());
    }//GEN-LAST:event_botonLimpiarActionPerformed

    private void botonComaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonComaActionPerformed
        String cadena = datos.getValorTecladoNumerico();
        if(!(cadena.contains("."))){
            if(cadena.length() == 0){
                datos.setValorTecladoNumerico("0.");
            }else{
                datos.setValorTecladoNumerico(cadena + ".");
            }
             textoTeclado.setText(datos.getValorTecladoNumerico());
        }
    }//GEN-LAST:event_botonComaActionPerformed

    private void botonEnterActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonEnterActionPerformed
        datos.setValorNumerico(Double.parseDouble(datos.getValorTecladoNumerico()));
        datos.setValorTecladoNumerico("");
        textoTeclado.setText(datos.getValorTecladoNumerico()); 
        botonEvent[8] = true;
    }//GEN-LAST:event_botonEnterActionPerformed

    //
    //botones gasolina
    //
    private void botonSeleccion1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonSeleccion1ActionPerformed
        datos.setPrecio(Double.parseDouble(textoPrecio1.getText()));
        textoPrecioPorLitro.setText(textoPrecio1.getText());
    }//GEN-LAST:event_botonSeleccion1ActionPerformed

    private void botonSeleccion2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonSeleccion2ActionPerformed
        datos.setPrecio(Double.parseDouble(textoPrecio2.getText()));
        textoPrecioPorLitro.setText(textoPrecio2.getText());
    }//GEN-LAST:event_botonSeleccion2ActionPerformed

    private void botonSeleccion3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonSeleccion3ActionPerformed
        datos.setPrecio(Double.parseDouble(textoPrecio3.getText()));
        textoPrecioPorLitro.setText(textoPrecio3.getText());
    }//GEN-LAST:event_botonSeleccion3ActionPerformed

    private void botonSeleccion5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonSeleccion5ActionPerformed
        datos.setPrecio(Double.parseDouble(textoPrecio5.getText()));
        textoPrecioPorLitro.setText(textoPrecio5.getText());
    }//GEN-LAST:event_botonSeleccion5ActionPerformed

    private void botonBombearActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonBombearActionPerformed
        botonEvent[9] = true;
    }//GEN-LAST:event_botonBombearActionPerformed

    private void botonSeleccion4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonSeleccion4ActionPerformed
        textoPrecioPorLitro.setText(textoPrecio4.getText());
        datos.setPrecio(Double.parseDouble(textoPrecio4.getText()));
    }//GEN-LAST:event_botonSeleccion4ActionPerformed

    private void botonOpcion8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonOpcion8ActionPerformed
        botonEvent[7] = true;
    }//GEN-LAST:event_botonOpcion8ActionPerformed

    private void botonOpcion7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonOpcion7ActionPerformed
        botonEvent[6] = true;
    }//GEN-LAST:event_botonOpcion7ActionPerformed

    private void botonOpcion6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonOpcion6ActionPerformed
        botonEvent[5] = true;
    }//GEN-LAST:event_botonOpcion6ActionPerformed

    private void botonOpcion5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonOpcion5ActionPerformed
        botonEvent[4] = true;
    }//GEN-LAST:event_botonOpcion5ActionPerformed

    private void botonOpcion4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonOpcion4ActionPerformed
        botonEvent[3] = true;
    }//GEN-LAST:event_botonOpcion4ActionPerformed

    private void botonOpcion3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonOpcion3ActionPerformed
        botonEvent[2] = true;
    }//GEN-LAST:event_botonOpcion3ActionPerformed

    private void botonOpcion2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonOpcion2ActionPerformed
        botonEvent[1] = true;
    }//GEN-LAST:event_botonOpcion2ActionPerformed

    //
    //botones opciones
    //
    private void botonOpcion1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonOpcion1ActionPerformed
        botonEvent[0] = true;
    }//GEN-LAST:event_botonOpcion1ActionPerformed

    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(InterfazGasolinera.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(InterfazGasolinera.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(InterfazGasolinera.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(InterfazGasolinera.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new InterfazGasolinera().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton boton0;
    private javax.swing.JButton boton1;
    private javax.swing.JButton boton2;
    private javax.swing.JButton boton3;
    private javax.swing.JButton boton4;
    private javax.swing.JButton boton5;
    private javax.swing.JButton boton6;
    private javax.swing.JButton boton7;
    private javax.swing.JButton boton8;
    private javax.swing.JButton boton9;
    private javax.swing.JButton botonBombear;
    private javax.swing.JButton botonBorrar;
    private javax.swing.JButton botonComa;
    private javax.swing.JButton botonEnter;
    private javax.swing.JButton botonLimpiar;
    private javax.swing.JButton botonOpcion1;
    private javax.swing.JButton botonOpcion2;
    private javax.swing.JButton botonOpcion3;
    private javax.swing.JButton botonOpcion4;
    private javax.swing.JButton botonOpcion5;
    private javax.swing.JButton botonOpcion6;
    private javax.swing.JButton botonOpcion7;
    private javax.swing.JButton botonOpcion8;
    private javax.swing.JButton botonSeleccion1;
    private javax.swing.JButton botonSeleccion2;
    private javax.swing.JButton botonSeleccion3;
    private javax.swing.JButton botonSeleccion4;
    private javax.swing.JButton botonSeleccion5;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JPanel jPanel8;
    private javax.swing.JLabel labelPrecio1;
    private javax.swing.JLabel labelPrecio2;
    private javax.swing.JLabel labelPrecio3;
    private javax.swing.JLabel labelPrecio4;
    private javax.swing.JLabel labelPrecio5;
    private javax.swing.JPanel panelOpciones;
    private javax.swing.JPanel panelPrecioCombustible;
    private javax.swing.JPanel panelTeclado;
    private javax.swing.JTextField textoLitros;
    private javax.swing.JTextField textoMenu;
    private javax.swing.JTextField textoOpcion1;
    private javax.swing.JTextField textoOpcion2;
    private javax.swing.JTextField textoOpcion3;
    private javax.swing.JTextField textoOpcion4;
    private javax.swing.JTextField textoOpcion5;
    private javax.swing.JTextField textoOpcion6;
    private javax.swing.JTextField textoOpcion7;
    private javax.swing.JTextField textoOpcion8;
    private javax.swing.JTextField textoPrecio;
    private javax.swing.JTextField textoPrecio1;
    private javax.swing.JTextField textoPrecio2;
    private javax.swing.JTextField textoPrecio3;
    private javax.swing.JTextField textoPrecio4;
    private javax.swing.JTextField textoPrecio5;
    private javax.swing.JTextField textoPrecioPorLitro;
    private javax.swing.JTextField textoTeclado;
    // End of variables declaration//GEN-END:variables
}
