/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package projectodieta;

/**
 *
 * @author damian
 */
public class Listado extends javax.swing.JFrame {

    MetodosDieta dieta = new MetodosDieta();
    
    public Listado() {
        initComponents();
        inicializar(dieta);
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        pestañaPrincipal = new javax.swing.JTabbedPane();
        jScrollPane1 = new javax.swing.JScrollPane();
        textoSemUno = new javax.swing.JTextArea();
        jScrollPane2 = new javax.swing.JScrollPane();
        textoSemDos = new javax.swing.JTextArea();
        jScrollPane3 = new javax.swing.JScrollPane();
        textoSemTres = new javax.swing.JTextArea();
        jScrollPane4 = new javax.swing.JScrollPane();
        textoSemCuatro = new javax.swing.JTextArea();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        pestañaPrincipal.setPreferredSize(new java.awt.Dimension(450, 300));
        pestañaPrincipal.setRequestFocusEnabled(false);

        textoSemUno.setBackground(new java.awt.Color(153, 255, 153));
        textoSemUno.setColumns(20);
        textoSemUno.setFont(new java.awt.Font("DejaVu Sans", 1, 12)); // NOI18N
        textoSemUno.setRows(5);
        jScrollPane1.setViewportView(textoSemUno);

        pestañaPrincipal.addTab("1ra Semana", jScrollPane1);

        textoSemDos.setBackground(new java.awt.Color(153, 255, 153));
        textoSemDos.setColumns(20);
        textoSemDos.setFont(new java.awt.Font("DejaVu Sans", 1, 12)); // NOI18N
        textoSemDos.setRows(5);
        jScrollPane2.setViewportView(textoSemDos);

        pestañaPrincipal.addTab("2da Semana", jScrollPane2);

        textoSemTres.setBackground(new java.awt.Color(153, 255, 153));
        textoSemTres.setColumns(20);
        textoSemTres.setFont(new java.awt.Font("DejaVu Sans", 1, 12)); // NOI18N
        textoSemTres.setRows(5);
        jScrollPane3.setViewportView(textoSemTres);

        pestañaPrincipal.addTab("3ra Semana", jScrollPane3);

        textoSemCuatro.setBackground(new java.awt.Color(153, 255, 153));
        textoSemCuatro.setColumns(20);
        textoSemCuatro.setFont(new java.awt.Font("DejaVu Sans", 1, 12)); // NOI18N
        textoSemCuatro.setRows(5);
        jScrollPane4.setViewportView(textoSemCuatro);

        pestañaPrincipal.addTab("4ta Semana", jScrollPane4);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(pestañaPrincipal, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(pestañaPrincipal, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void inicializar(MetodosDieta dieta){
        pestañaPrincipal.setEnabledAt(0, false);
        pestañaPrincipal.setEnabledAt(1, false);
        pestañaPrincipal.setEnabledAt(2, false);
        pestañaPrincipal.setEnabledAt(3, false);
        
        switch(dieta.getSeleccionModo()){
            case 1://dia
                switch(dieta.getIndexSemana()){
                    case 0:
                        textoSemUno.setText(dieta.getTextoDia());
                        pestañaPrincipal.setEnabledAt(0, true);
                        textoSemUno.setCaretPosition(0);
                        pestañaPrincipal.setSelectedIndex(0);
                        break;
                    case 1:
                        textoSemDos.setText(dieta.getTextoDia());
                        pestañaPrincipal.setEnabledAt(1, true);
                        textoSemDos.setCaretPosition(0);
                        pestañaPrincipal.setSelectedIndex(1);
                        break;
                    case 2:
                        textoSemTres.setText(dieta.getTextoDia());
                        pestañaPrincipal.setEnabledAt(2, true);
                        textoSemTres.setCaretPosition(0);
                        pestañaPrincipal.setSelectedIndex(2);
                        break;
                    case 3:
                        textoSemCuatro.setText(dieta.getTextoDia());
                        pestañaPrincipal.setEnabledAt(3, true);
                        textoSemCuatro.setCaretPosition(0);
                        pestañaPrincipal.setSelectedIndex(3);
                        break;
                }
                break;
                
            case 2://semana
                switch(dieta.getIndexSemana()){
                    case 0:
                        textoSemUno.setText(dieta.getTextoSemana(0));
                        pestañaPrincipal.setEnabledAt(0, true);
                        textoSemUno.setCaretPosition(0);
                        pestañaPrincipal.setSelectedIndex(0);
                        break;
                    case 1:
                        textoSemDos.setText(dieta.getTextoSemana(1));
                        pestañaPrincipal.setEnabledAt(1, true);
                        textoSemDos.setCaretPosition(0);
                        pestañaPrincipal.setSelectedIndex(1);
                        break;
                    case 2:
                        textoSemTres.setText(dieta.getTextoSemana(2));
                        pestañaPrincipal.setEnabledAt(2, true);
                        textoSemTres.setCaretPosition(0);
                        pestañaPrincipal.setSelectedIndex(2);
                        break;
                    case 3:
                        textoSemCuatro.setText(dieta.getTextoSemana(3));
                        pestañaPrincipal.setEnabledAt(3, true);
                        textoSemCuatro.setCaretPosition(0);
                        pestañaPrincipal.setSelectedIndex(3);
                        break;
                }
                break;
                
            case 3://mes
                
                pestañaPrincipal.setEnabledAt(0, true);
                pestañaPrincipal.setEnabledAt(1, true);
                pestañaPrincipal.setEnabledAt(2, true);
                pestañaPrincipal.setEnabledAt(3, true);
                textoSemUno.setText(dieta.getTextoSemana(0));
                textoSemUno.setCaretPosition(0);
                textoSemDos.setText(dieta.getTextoSemana(1));
                textoSemDos.setCaretPosition(0);
                textoSemTres.setText(dieta.getTextoSemana(2));
                textoSemTres.setCaretPosition(0);
                textoSemCuatro.setText(dieta.getTextoSemana(3));
                textoSemCuatro.setCaretPosition(0);
                break;
                
            default:
                break;
        }
    }
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Listado.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Listado.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Listado.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Listado.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Listado().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JTabbedPane pestañaPrincipal;
    private javax.swing.JTextArea textoSemCuatro;
    private javax.swing.JTextArea textoSemDos;
    private javax.swing.JTextArea textoSemTres;
    private javax.swing.JTextArea textoSemUno;
    // End of variables declaration//GEN-END:variables
}
